[theme]
# Primary accent color for interactive elements
primaryColor = "#1E3A8A"

# Background color for the main content area
backgroundColor = "#F9FAFB"

# Background color used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#F9FAFB"

# Color used for almost all text
textColor = "#1F2937"

# Font family for all text in the app, except code blocks
font = "sans serif"

[server]
# Enable the built-in theme
enableXsrfProtection = true
enableCORS = false 